# Font
font_family     	family="FiraCode Nerd Font Mono" style=Light
bold_font       	auto
italic_font     	auto
bold_italic_font	auto
font_size		12

# Color - Nord color scheme
# Foreground / Background
foreground		#D8DEE9
background		#2E3440

# Normal colors
color0			#3B4252
color1			#BF616A
color2			#A3BE8C
color3			#EBCB8B
color4			#81A1C1
color5			#B48EAD
color6			#88C0D0
color7			#E5E9F0

# Bright colors
color8			#4C566A
color9			#BF616A
color10			#A3BE8C
color11			#EBCB8B
color12			#81A1C1
color13			#B48EAD
color14			#8FBCBB
color15			#ECEFF4

# Scrollbar
scrollbar_handle_color	#5E5C87
scrollbar_track_color	#2E3440

# Size
window_padding_width	10
scrollbar_gap		0.5
scrollbar_width		0.5
scrollbar_hover_width	0.5

# Extra
shell_integration	no-cursor
cursor_shape		block
cursor_shape_unfocused	hollow
enable_audio_bell	no
disable_ligatures	always

# Shortcuts
clear_all_shortcuts	yes
map ctrl+shift+c	copy_to_clipboard
map ctrl+shift+v	paste_from_clipboard
map ctrl+plus		change_font_size all +1.0
map ctrl+minus		change_font_size all -1.0
map ctrl+shift+plus	change_font_size all 12
map ctrl+shift+minus	change_font_size all 12
