# Font
# font_family     	family="FiraCode Nerd Font Mono" style=Light
bold_font       	auto
italic_font     	auto
bold_italic_font	auto
font_size		18

# Color
background		#1E1E1E
scrollbar_handle_color	#195092
scrollbar_track_color	#1E1E1E

# Size
window_padding_width	10
scrollbar_gap		0.5
scrollbar_width		0.5
scrollbar_hover_width	0.5

# Extra
shell_integration	no-cursor
cursor_shape		block
cursor_shape_unfocused	hollow
enable_audio_bell	no
disable_ligatures	always

# Shortcuts
clear_all_shortcuts	yes
map ctrl+shift+c	copy_to_clipboard
map ctrl+shift+v	paste_from_clipboard
map ctrl+plus		change_font_size all +1.0
map ctrl+minus		change_font_size all -1.0
map ctrl+shift+plus	change_font_size all 12
map ctrl+shift+minus	change_font_size all 12
