# Font
font_family     	family="FiraCode Nerd Font Mono" style=Light
bold_font       	auto
italic_font     	auto
bold_italic_font	auto
font_size		12.0

# Color
background		#1E1E1E
scrollbar_handle_color	#195092
scrollbar_track_color	#1E1E1E

# Size
window_padding_width	10
scrollbar_gap		0.5
scrollbar_width		0.5
scrollbar_hover_width	0.5

# Extra
shell_integration	no-cursor
cursor_shape		block
cursor_shape_unfocused	hollow
enable_audio_bell	no

# Shortcuts
clear_all_shortcuts	yes
