after-startup-command = [
    'exec-and-forget borders active_color=0xff195092 inactive_color=0x00000000 width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-orientation = 'auto'
default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# All possible modifiers: cmd, alt, ctrl, shift
[mode.main.binding]
ctrl-enter = 'exec-and-forget open -na /Applications/Alacritty.app/'
ctrl-w = 'exec-and-forget open -na /Applications/Chromium.app/'
ctrl-e = 'exec-and-forget open -n /Users/Used'
ctrl-q = 'close'

ctrl-left = 'focus left'
ctrl-right = 'focus right'
ctrl-up = 'focus up'
ctrl-down = 'focus down'

ctrl-shift-left = 'move left'
ctrl-shift-right = 'move right'
ctrl-shift-up = 'move up'
ctrl-shift-down = 'move down'

cmd-ctrl-left = 'resize width -50'
cmd-ctrl-right = 'resize width +50'
cmd-ctrl-up = 'resize height +50'
cmd-ctrl-down = 'resize height -50'

ctrl-f = 'fullscreen'
ctrl-space = 'layout floating tiling'
ctrl-s = 'layout tiles horizontal vertical'

# ctrl-1 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 1 workspace'
# ctrl-2 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 2 workspace'
# ctrl-3 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 3 workspace'
# ctrl-4 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 4 workspace'
# ctrl-5 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 5 workspace'
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

# cmd-ctrl-1 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 1 move-node-to-workspace'
# cmd-ctrl-2 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 2 move-node-to-workspace'
# cmd-ctrl-3 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 3 move-node-to-workspace'
# cmd-ctrl-4 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 4 move-node-to-workspace'
# cmd-ctrl-5 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 5 move-node-to-workspace'
cmd-ctrl-1 = 'move-node-to-workspace 1'
cmd-ctrl-2 = 'move-node-to-workspace 2'
cmd-ctrl-3 = 'move-node-to-workspace 3'
cmd-ctrl-4 = 'move-node-to-workspace 4'
cmd-ctrl-5 = 'move-node-to-workspace 5'
cmd-ctrl-6 = 'move-node-to-workspace 6'
cmd-ctrl-7 = 'move-node-to-workspace 7'
cmd-ctrl-8 = 'move-node-to-workspace 8'
cmd-ctrl-9 = 'move-node-to-workspace 9'
cmd-ctrl-0 = 'move-node-to-workspace 10'

cmd-shift-r = 'reload-config'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 2
7 = 2
8 = 2
9 = 2
10 = 2

[mode.resize.binding]
enter = 'mode main'
esc = 'mode main'

# [[on-window-detected]]
# if.app-id = 'com.apple.iphonesimulator'
# run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.chromium.Chromium'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = 'move-node-to-workspace 1'

