after-startup-command = [
    'exec-and-forget borders active_color=0xff195092 inactive_color=0x00000000 width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-orientation = 'auto'
default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# All possible modifiers: cmd, alt, ctrl, shift
[mode.main.binding]
cmd-enter = 'exec-and-forget open -na /Applications/Alacritty.app/'
cmd-w = 'exec-and-forget open -na /Applications/Firefox.app/'
cmd-e = 'exec-and-forget open -n /Users/Used'
cmd-q = 'close'

cmd-left = 'focus left'
cmd-right = 'focus right'
cmd-up = 'focus up'
cmd-down = 'focus down'

cmd-shift-left = 'move left'
cmd-shift-right = 'move right'
cmd-shift-up = 'move up'
cmd-shift-down = 'move down'

cmd-ctrl-left = 'resize width -50'
cmd-ctrl-right = 'resize width +50'
cmd-ctrl-up = 'resize height +50'
cmd-ctrl-down = 'resize height -50'

cmd-f = 'fullscreen'
cmd-space = 'layout floating tiling'
cmd-s = 'layout tiles horizontal h_accordion'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-ctrl-1 = 'move-node-to-workspace 1'
cmd-ctrl-2 = 'move-node-to-workspace 2'
cmd-ctrl-3 = 'move-node-to-workspace 3'
cmd-ctrl-4 = 'move-node-to-workspace 4'
cmd-ctrl-5 = 'move-node-to-workspace 5'
cmd-ctrl-6 = 'move-node-to-workspace 6'
cmd-ctrl-7 = 'move-node-to-workspace 7'
cmd-ctrl-8 = 'move-node-to-workspace 8'
cmd-ctrl-9 = 'move-node-to-workspace 9'
cmd-ctrl-0 = 'move-node-to-workspace 10'

cmd-shift-r = 'reload-config'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 2
7 = 2
8 = 2
9 = 2
10 = 2

[mode.resize.binding]
enter = 'mode main'
esc = 'mode main'

# [[on-window-detected]]
# if.app-id = 'com.apple.iphonesimulator'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-id = 'com.tinyspeck.slackmacgap'
# run = 'move-node-to-workspace 2'

# [[on-window-detected]]
# if.app-id = 'com.chromium.Chromium'
# run = 'move-node-to-workspace 6'

# [[on-window-detected]]
# if.app-id = 'com.electron.dockerdesktop'
# run = 'move-node-to-workspace 1'

