after-startup-command = [
    'exec-and-forget borders active_color=0xff195092 inactive_color=0x00000000 width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-orientation = 'auto'
default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
alt-enter = 'exec-and-forget open -na /Applications/Alacritty.app/'
alt-w = 'exec-and-forget open -na /Applications/Chromium.app/'
alt-e = 'exec-and-forget open -n /Users/Used'

alt-left = 'focus left'
alt-right = 'focus right'
alt-up = 'focus up'
alt-down = 'focus down'

alt-shift-left = 'move left'
alt-shift-right = 'move right'
alt-shift-up = 'move up'
alt-shift-down = 'move down'

alt-ctrl-left = 'resize width -50'
alt-ctrl-right = 'resize width +50'
alt-ctrl-up = 'resize height +50'
alt-ctrl-down = 'resize height -50'

alt-f = 'fullscreen'
alt-space = 'layout floating tiling'
alt-s = 'layout tiles horizontal vertical'

alt-1 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 1 workspace'
alt-2 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 2 workspace'
alt-3 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 3 workspace'
alt-4 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 4 workspace'
alt-5 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 5 workspace'

alt-shift-1 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 1 move-node-to-workspace'
alt-shift-2 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 2 move-node-to-workspace'
alt-shift-3 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 3 move-node-to-workspace'
alt-shift-4 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 4 move-node-to-workspace'
alt-shift-5 = 'exec-and-forget sh /Users/Used/.config/aerospace/workspace.sh 5 move-node-to-workspace'

alt-shift-r = 'reload-config'
alt-r = 'mode resize'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 2
7 = 2
8 = 2
9 = 2
10 = 2

[mode.resize.binding]
enter = 'mode main'
esc = 'mode main'

# [[on-window-detected]]
# if.app-id = 'com.apple.iphonesimulator'
# run = 'layout floating'
