#!/usr/bin/env sh

# Layout
yabai -m config layout			bsp
yabai -m config top_padding		8
yabai -m config bottom_padding		8
yabai -m config left_padding		8
yabai -m config right_padding		8
yabai -m config window_gap		8

# Options
yabai -m config window_topmost		on
yabai -m config focus_follows_mouse	autofocus
yabai -m config mouse_modifier		cmd

# Rules
yabai -m rule --add app!="^(Alacritty|Brave Browser|Code|Discord|Docker Desktop|Finder|Slack)$" manage=off
