#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout
yabai -m config layout			bsp
yabai -m config top_padding		8
yabai -m config bottom_padding		8
yabai -m config left_padding		8
yabai -m config right_padding		8
yabai -m config window_gap		8

# Options
yabai -m config window_topmost		on
yabai -m config window_shadow		float
yabai -m config focus_follows_mouse	autofocus
yabai -m config mouse_modifier		cmd
yabai -m config window_placement	second_child

# Rules
yabai -m rule --add app="Simulator" sticky=on layer=above manage=off
yabai -m rule --add app="qemu-system-aarch64" sticky=on layer=above manage=off
yabai -m rule --add app="System Settings" sticky=on layer=above manage=off

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref|Settings)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

#yabai -m rule --add label="Alacritty" manage=on layer=below
#yabai -m rule --add label="Brave Browser" manage=on layer=below
#yabai -m rule --add label="Code" manage=on layer=below
#yabai -m rule --add app="Dbeaver" manage=on layer=below
#yabai -m rule --add app="Discord" manage=on layer=below
#yabai -m rule --add app="Docker Desktop" manage=on layer=below
#yabai -m rule --add app="Finder" manage=on layer=below
#yabai -m rule --add label="Microsoft Teams" manage=on layer=below
#yabai -m rule --add app="Slack" manage=on layer=below
#yabai -m rule --add app="Xcode" manage=on layer=below
