#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout
yabai -m config layout			bsp
yabai -m config top_padding		8
yabai -m config bottom_padding		8
yabai -m config left_padding		8
yabai -m config right_padding		8
yabai -m config window_gap		8

# Options
yabai -m config window_topmost		on
yabai -m config window_shadow		off
yabai -m config focus_follows_mouse	autofocus
yabai -m config mouse_modifier		cmd
yabai -m config window_placement	second_child

# Rules
tiling="(Alacritty|Brave Browser|Code|DBeaver|Discord|Docker Desktop|Finder|Microsoft Teams|Slack|Xcode)"
yabai -m rule --add app=".*" layer=below
yabai -m rule --add app!="^${tiling}$" manage=off
