Net/ThemeName "adw-gtk3-dark"
Net/IconThemeName "Flat-Remix-Green-Light-darkPanel"
Gtk/CursorThemeName "Breeze_Light"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
